lsi: false
safe: true
source: docs/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-jemoji
- jekyll-remote-theme 
