# Welcome to Jekyll!

title: nf-ducken Documentation
email: lina.kim@hest.ethz.ch
repository: bokulich-lab/nf-ducken
description: >- # this means to ignore newlines until "baseurl:" 
 nf-ducken is a scalable platform for microbiome bioinformatics analysis using QIIME 2 and Nextflow.
baseurl: "/nf-ducken/docs"
url: "https://bokulich-lab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
destination: _site/
twitter_username: linathekim
github_username:  bokulich-lab

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata

