# Welcome to Jekyll!

title: nf-ducken Documentation
email: lina.kim@hest.ethz.ch
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "docs/" # the subpath of your site, e.g. /blog
destination: docs/_site
#url: "https://bokulich-lab.github.io/nf-ducken" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: linathekim
github_username:  lina-kim

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
